[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = { version = "0.11", features = ["serde"] }
tokio = { version = "1.43.0", features = ["full"] }
tokio-util = { version = "0.6.7", features = ["codec", "io"] }
rand = "0.8.5"
uuid = "1.11.1"
